subnet_cidr         = "10.0.0.0/24"
pods_cidr           = "10.1.0.0/21"
services_cidr       = "10.2.0.0/24"
project_id         = "black-hole-visualizer-project"
region             = "northamerica-northeast2"
env                = "dev"
terraform_admin_sa = "bh-vis-admin@black-hole-visualizer-project.iam.gserviceaccount.com"
